# Generated by Matugen - do not edit manually.

set -g fish_color_command {{colors.primary.default.hex}}
set -g fish_color_param {{colors.on_surface.default.hex}}
set -g fish_color_comment {{colors.outline.default.hex}}
set -g fish_color_error {{colors.error.default.hex}}
set -g fish_color_quote {{colors.secondary.default.hex}}
set -g fish_color_cwd {{colors.tertiary.default.hex}}
set -g fish_color_search_match --background={{colors.secondary_container.default.hex}} --foreground={{colors.on_secondary_container.default.hex}}
