#!/usr/bin/env bash
set -euo pipefail

COLORS_JSON="${1:-$HOME/.local/state/quickshell/user/generated/colors.json}"
OUT_FILE="${2:-$HOME/.config/kamlab/zellij/themes/matugen.kdl}"

if [[ ! -f "$COLORS_JSON" ]]; then
  echo "sync-zellij-theme: missing colors json: $COLORS_JSON" >&2
  exit 1
fi

for tool in jq; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "sync-zellij-theme: missing dependency: $tool" >&2
    exit 1
  }
done

hex_to_rgb() {
  local hex="${1#\#}"
  if [[ ! "$hex" =~ ^[0-9A-Fa-f]{6}$ ]]; then
    echo "0 0 0"
    return
  fi
  printf "%d %d %d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

get_color() {
  local key="$1"
  jq -r --arg k "$key" '.[$k] // empty' "$COLORS_JSON"
}

fg_hex="$(get_color on_surface)"
bg_hex="$(get_color surface)"
red_hex="$(get_color error)"
green_hex="$(get_color tertiary)"
yellow_hex="$(get_color secondary)"
blue_hex="$(get_color primary)"
magenta_hex="$(get_color tertiary_container)"
orange_hex="$(get_color error_container)"
cyan_hex="$(get_color secondary_container)"
black_hex="$(get_color surface_container_lowest)"
white_hex="$(get_color on_surface)"

mkdir -p "$(dirname "$OUT_FILE")"

cat > "$OUT_FILE" <<KDL
// Generated by scripts/sync-zellij-theme.sh from $COLORS_JSON

themes {
  matugen {
    fg $(hex_to_rgb "$fg_hex")
    bg $(hex_to_rgb "$bg_hex")
    red $(hex_to_rgb "$red_hex")
    green $(hex_to_rgb "$green_hex")
    yellow $(hex_to_rgb "$yellow_hex")
    blue $(hex_to_rgb "$blue_hex")
    magenta $(hex_to_rgb "$magenta_hex")
    orange $(hex_to_rgb "$orange_hex")
    cyan $(hex_to_rgb "$cyan_hex")
    black $(hex_to_rgb "$black_hex")
    white $(hex_to_rgb "$white_hex")
  }
}
KDL

echo "sync-zellij-theme: wrote $OUT_FILE"
