-- Generated by Matugen - do not edit manually.

return {
  apply = function()
    local p = {
      bg = "{{colors.surface.default.hex}}",
      fg = "{{colors.on_surface.default.hex}}",
      accent = "{{colors.primary.default.hex}}",
      comment = "{{colors.outline.default.hex}}",
      error = "{{colors.error.default.hex}}",
      warn = "{{colors.secondary.default.hex}}",
      info = "{{colors.tertiary.default.hex}}",
      selection = "{{colors.secondary_container.default.hex}}",
      selection_fg = "{{colors.on_secondary_container.default.hex}}",
    }

    vim.api.nvim_set_hl(0, "Normal", { fg = p.fg, bg = p.bg })
    vim.api.nvim_set_hl(0, "NormalFloat", { fg = p.fg, bg = p.bg })
    vim.api.nvim_set_hl(0, "Visual", { fg = p.selection_fg, bg = p.selection })
    vim.api.nvim_set_hl(0, "Comment", { fg = p.comment, italic = true })
    vim.api.nvim_set_hl(0, "DiagnosticError", { fg = p.error })
    vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = p.warn })
    vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = p.info })
    vim.api.nvim_set_hl(0, "CursorLineNr", { fg = p.accent, bold = true })
  end,
}
